# Generated by the LlamaPress scaffold templates (llama_bot_rails).
class OrdersController < ApplicationController
  include LlamaBotRails::ScaffoldFiltering

  before_action :set_order, only: %i[ show edit update destroy update_status ]

  # GET /orders
  def index
    scope = llama_filtered_scope(base_scope,
      search_columns: %i[ status customer_name customer_class customer_phone ],
      boolean_columns: [],
      date_column: :created_at)
    @pagy, @orders = llama_paginate(scope.order(created_at: :desc))
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def update_status
    new_status = params[:status].to_s
    if %w[Menunggu Siap_Diambil Selesai Dibatalkan].include?(new_status)
      @order.update!(status: new_status)
      redirect_to orders_path, notice: "Pesanan ##{@order.id} → #{@order.status_label}"
    else
      redirect_to orders_path, alert: "Status tidak valid"
    end
  end

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { llama_after_save_redirect(@order, notice: "Order was successfully created.") }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { llama_after_save_redirect(@order, notice: "Order was successfully updated.") }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy!
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    def base_scope
      Order.all
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:customer_name, :customer_class, :customer_phone, :note, :status, :total_amount)
    end
end
